# Generated by Django 5.0.4 on 2024-04-21 10:09

import data_management.models
import django.db.models.deletion
import django_jsonfield_backport.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.IntegerField(choices=[(0, 'None'), (1, 'Unknown'), (2, 'Leak'), (3, 'Walking'), (4, 'Animal'), (5, 'Digging'), (6, 'Climbing'), (7, 'Vehicle'), (8, 'Excavation'), (9, 'Vibration'), (10, 'Pressure Wave'), (11, 'Crawling'), (12, 'Fence Cut'), (13, 'Impact'), (14, 'HDD'), (15, 'Train'), (16, 'Elephant'), (50, 'Temperature Low'), (51, 'Temperature High'), (100, 'Cut Fibre')], default=0)),
                ('event_description', models.TextField(blank=True, null=True)),
                ('event_details', django_jsonfield_backport.models.JSONField(default=dict)),
                ('file', models.FileField(upload_to=data_management.models.upload_to_fos_directory)),
                ('fos_serial_number', models.CharField(max_length=100)),
                ('kml_map_data', models.TextField(blank=True, null=True)),
                ('channel', models.IntegerField()),
                ('number_of_bins', models.IntegerField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('adc_clock', models.IntegerField()),
                ('pulse_repetition_rate', models.IntegerField()),
                ('pulse_width', models.IntegerField()),
                ('file_recording_rev', models.IntegerField()),
                ('number_data_rows', models.IntegerField()),
                ('dts_num_averages', models.IntegerField()),
                ('dts_resolution', models.FloatField()),
                ('dts_sweep_number', models.IntegerField()),
                ('dts_min_temp', models.IntegerField()),
                ('dts_max_temp', models.IntegerField()),
                ('dts_start_frequency', models.FloatField()),
                ('dts_end_frequency', models.FloatField()),
                ('dts_units', models.IntegerField()),
                ('das_filter_cut_in_freq', models.FloatField(blank=True, null=True)),
                ('das_filter_cut_out_freq', models.FloatField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
