# Generated by Django 5.0.4 on 2024-04-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='event_details',
            field=models.JSONField(default=dict),
        ),
    ]
