# Generated by Django 5.0.4 on 2024-04-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_alter_fileupload_event_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='dts_end_frequency',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='dts_max_temp',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='dts_min_temp',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='dts_num_averages',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='dts_resolution',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='dts_start_frequency',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='dts_sweep_number',
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='dts_units',
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='event_details',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='event_type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Unknown'), (2, 'Leak'), (3, 'Walking'), (4, 'Animal'), (5, 'Digging'), (6, 'Climbing'), (7, 'Vehicle'), (8, 'Excavation'), (9, 'Vibration'), (10, 'Pressure Wave'), (11, 'Crawling'), (12, 'Fence Cut'), (13, 'Impact'), (14, 'HDD'), (15, 'Train'), (16, 'Elephant'), (100, 'Cut Fibre')], default=0),
        ),
    ]
