# Generated by Django 5.0.4 on 2024-04-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_remove_fileupload_dts_end_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='fibre_calibrations',
            field=models.FileField(blank=True, null=True, upload_to='calibrations/'),
        ),
    ]
