# Generated by Django 5.0.4 on 2024-04-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_fileupload_fibre_calibrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='fibre_calibrations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
