# Generated by Django 5.0.4 on 2024-05-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_alter_fileupload_fibre_calibrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fileupload',
            name='channel',
        ),
    ]
