# Generated by Django 5.0.4 on 2024-04-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_name_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='fosuser',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
